shell = "/bin/zsh"

[colors.bright]
black = "0x4a3637"
blue = "0x535c5c"
cyan = "0x6d715e"
green = "0x7b8748"
magenta = "0x775759"
red = "0xd17b49"
white = "0xc0a48b"
yellow = "0xaf865a"

[colors.normal]
black = "0x4a3637"
blue = "0x535c5c"
cyan = "0x6d715e"
green = "0x7b8748"
magenta = "0x775759"
red = "0xd17b49"
white = "0xc0a48b"
yellow = "0xaf865a"

[colors.primary]
background = "0x090909"
foreground = "0xc0a48b"

[font]
size = 10.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font "
style = "Regular"
