#! /bin/sh

bash ~/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
hsetroot -solid '#151515'
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/.wallpaper.png
picom &
/usr/bin/dunst &
notify-send "Hello Shiva" "Welcome to arch."

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#2e313d'
bspc config focused_border_color '#5b5f71'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
